// <auto-generated />
using System;
using Acutis.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acutis.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acutis.Domain.Entities.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrescribedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrescribedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("Prescription", (string)null);
                });

            modelBuilder.Entity("Acutis.Domain.Entities.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AdmissionFormCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdmissionFormCompletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionPhase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AdmittedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArrivalPhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataQuality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfAdmission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DepositReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DischargePhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FinanceOfficerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasMedicalCard")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMobilityIssue")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPrivateInsurance")
                        .HasColumnType("bit");

                    b.Property<bool>("HasProbationRequirement")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmissionFormComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPreviousResident")
                        .HasColumnType("bit");

                    b.Property<string>("MedicalCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("bit");

                    b.Property<string>("NextOfKinFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextOfKinPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextOfKinSecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NurseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhotoDeclined")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoDeclinedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredStepDownHouse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrimaryAddictionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrivateMedicalInsuranceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrivateMedicalInsuranceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProbationRequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionnairesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReligiousAffiliationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CountryId");

                    b.HasIndex("PrimaryAddictionId");

                    b.HasIndex("PrivateMedicalInsuranceProviderId");

                    b.HasIndex("ProbationRequirementId");

                    b.HasIndex("ReligiousAffiliationId");

                    b.ToTable("Resident", (string)null);
                });

            modelBuilder.Entity("Acutis.Domain.Entities.ResidentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("ResidentId");

                    b.ToTable("ResidentDocument", (string)null);
                });

            modelBuilder.Entity("Acutis.Domain.Entities.ResidentPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("ResidentPhoto", (string)null);
                });

            modelBuilder.Entity("Acutis.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasOwnWC")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpiateDetox")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQuarantine")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfResidents")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("Acutis.Domain.Lookups.Addiction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddictionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddictionTypeId");

                    b.ToTable("Addiction", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("568f321c-f08d-49eb-b895-24c0fff76147"),
                            Category = "Substance",
                            Name = "Alcohol"
                        },
                        new
                        {
                            Id = new Guid("b0785d0f-d15e-4422-9a20-55071b8846e4"),
                            Category = "Substance",
                            Name = "Cocaine"
                        },
                        new
                        {
                            Id = new Guid("bcdaef1c-e816-48e0-86cd-22bfd0409163"),
                            Category = "Behavioural",
                            Name = "Gambling"
                        });
                });

            modelBuilder.Entity("Acutis.Domain.Lookups.AddictionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AddictionType", (string)null);
                });

            modelBuilder.Entity("Acutis.Domain.Lookups.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Demonym")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c241b3b-bbef-47ef-ad6d-6a485790f802"),
                            CountryCode = "IE",
                            CountryName = "Ireland",
                            Demonym = "Irish"
                        });
                });

            modelBuilder.Entity("Acutis.Domain.Lookups.County", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("County", (string)null);
                });

            modelBuilder.Entity("Acutis.Domain.Lookups.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentType", (string)null);
                });

            modelBuilder.Entity("Acutis.Domain.Lookups.MedicalInsuranceProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedicalInsuranceProvider", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f956cb97-16eb-45d3-8823-9bab84177c5c"),
                            Name = "VHI"
                        },
                        new
                        {
                            Id = new Guid("505c437e-b9e3-47da-9735-efaa9fe3bd5c"),
                            Name = "Irish Life"
                        });
                });

            modelBuilder.Entity("Acutis.Domain.Lookups.ProbationRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ProbationType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8655eed-cca5-428b-a22f-baffdadde3c9"),
                            Requirement = "Curfew"
                        },
                        new
                        {
                            Id = new Guid("5ebe9b43-1e7e-4a64-bbe1-8eb2f1884d0b"),
                            Requirement = "Weekly Check-in"
                        });
                });

            modelBuilder.Entity("Acutis.Domain.Lookups.ReligiousAffiliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReligiousAffiliation", (string)null);
                });

            modelBuilder.Entity("Acutis.Domain.ValueObjects.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CountyId");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("ResidentAddiction", b =>
                {
                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddictionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResidentId", "AddictionId");

                    b.HasIndex("AddictionId");

                    b.ToTable("ResidentAddiction", (string)null);
                });

            modelBuilder.Entity("Acutis.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("Acutis.Domain.Entities.Resident", "Resident")
                        .WithMany("Prescriptions")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Acutis.Domain.Entities.Resident", b =>
                {
                    b.HasOne("Acutis.Domain.ValueObjects.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Acutis.Domain.Lookups.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Acutis.Domain.Lookups.Addiction", "PrimaryAddiction")
                        .WithMany()
                        .HasForeignKey("PrimaryAddictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acutis.Domain.Lookups.MedicalInsuranceProvider", "PrivateMedicalInsuranceProvider")
                        .WithMany()
                        .HasForeignKey("PrivateMedicalInsuranceProviderId");

                    b.HasOne("Acutis.Domain.Lookups.ProbationRequirement", "ProbationRequirement")
                        .WithMany()
                        .HasForeignKey("ProbationRequirementId");

                    b.HasOne("Acutis.Domain.Lookups.ReligiousAffiliation", "ReligiousAffiliation")
                        .WithMany()
                        .HasForeignKey("ReligiousAffiliationId");

                    b.Navigation("Address");

                    b.Navigation("Country");

                    b.Navigation("PrimaryAddiction");

                    b.Navigation("PrivateMedicalInsuranceProvider");

                    b.Navigation("ProbationRequirement");

                    b.Navigation("ReligiousAffiliation");
                });

            modelBuilder.Entity("Acutis.Domain.Entities.ResidentDocument", b =>
                {
                    b.HasOne("Acutis.Domain.Lookups.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acutis.Domain.Entities.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Acutis.Domain.Entities.ResidentPhoto", b =>
                {
                    b.HasOne("Acutis.Domain.Entities.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Acutis.Domain.Lookups.Addiction", b =>
                {
                    b.HasOne("Acutis.Domain.Lookups.AddictionType", "AddictionType")
                        .WithMany()
                        .HasForeignKey("AddictionTypeId");

                    b.Navigation("AddictionType");
                });

            modelBuilder.Entity("Acutis.Domain.Lookups.County", b =>
                {
                    b.HasOne("Acutis.Domain.Lookups.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Acutis.Domain.ValueObjects.Address", b =>
                {
                    b.HasOne("Acutis.Domain.Lookups.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acutis.Domain.Lookups.County", "County")
                        .WithMany()
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("County");
                });

            modelBuilder.Entity("ResidentAddiction", b =>
                {
                    b.HasOne("Acutis.Domain.Lookups.Addiction", null)
                        .WithMany()
                        .HasForeignKey("AddictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acutis.Domain.Entities.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Acutis.Domain.Entities.Resident", b =>
                {
                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
