import type { MapDocument } from "@/areas/config/mapDesigner/types";

export const sampleDetoxReferenceMap: MapDocument = {
  id: "detox_reference_derived",
  name: "Detox Reference Derived",
  world: {
    width: 1600,
    height: 1050,
  },
  artefacts: [
    {
      id: "zone_courtyard",
      type: "zone",
      geometry: { kind: "rect", x: 560, y: 180, width: 420, height: 260 },
      labelKey: "mapDesigner.sample.courtyard",
      labelOverride: "Courtyard",
    },
    {
      id: "room_entrance",
      type: "room",
      geometry: {
        kind: "polygon",
        points: [
          { x: 200, y: 340 },
          { x: 270, y: 270 },
          { x: 340, y: 340 },
          { x: 270, y: 410 },
        ],
      },
      labelKey: "mapDesigner.sample.mainEntrance",
      labelOverride: "Main Entrance",
    },
    {
      id: "room_1",
      type: "room",
      geometry: { kind: "rect", x: 235, y: 520, width: 95, height: 90 },
      labelKey: "mapDesigner.sample.rm1",
      labelOverride: "1",
    },
    {
      id: "room_2",
      type: "room",
      geometry: { kind: "rect", x: 330, y: 520, width: 95, height: 90 },
      labelKey: "mapDesigner.sample.rm2",
      labelOverride: "2",
    },
    {
      id: "room_3",
      type: "room",
      geometry: { kind: "rect", x: 425, y: 520, width: 95, height: 90 },
      labelKey: "mapDesigner.sample.rm3",
      labelOverride: "3",
    },
    {
      id: "room_4",
      type: "room",
      geometry: { kind: "rect", x: 520, y: 520, width: 95, height: 90 },
      labelKey: "mapDesigner.sample.rm4",
      labelOverride: "4",
    },
    {
      id: "room_5",
      type: "room",
      geometry: { kind: "rect", x: 615, y: 520, width: 95, height: 90 },
      labelKey: "mapDesigner.sample.rm5",
      labelOverride: "5",
    },
    {
      id: "room_sa1",
      type: "room",
      geometry: { kind: "rect", x: 410, y: 610, width: 170, height: 55 },
      labelKey: "mapDesigner.sample.sa1",
      labelOverride: "SA1",
    },
    {
      id: "room_lc1",
      type: "room",
      geometry: { kind: "rect", x: 580, y: 640, width: 85, height: 70 },
      labelKey: "mapDesigner.sample.lc1",
      labelOverride: "LC1",
    },
    {
      id: "room_waiting",
      type: "room",
      geometry: { kind: "rect", x: 580, y: 710, width: 95, height: 85 },
      labelKey: "mapDesigner.sample.waiting",
      labelOverride: "Waiting",
    },
    {
      id: "room_utility",
      type: "room",
      geometry: { kind: "rect", x: 580, y: 795, width: 95, height: 95 },
      labelKey: "mapDesigner.sample.utility",
      labelOverride: "Utility",
    },
    {
      id: "room_ns",
      type: "room",
      geometry: { kind: "rect", x: 740, y: 515, width: 120, height: 90 },
      labelKey: "mapDesigner.sample.ns",
      labelOverride: "NS",
    },
    {
      id: "room_tr",
      type: "room",
      geometry: { kind: "rect", x: 860, y: 515, width: 120, height: 90 },
      labelKey: "mapDesigner.sample.tr",
      labelOverride: "TR",
    },
    {
      id: "room_op",
      type: "room",
      geometry: { kind: "rect", x: 740, y: 605, width: 120, height: 90 },
      labelKey: "mapDesigner.sample.op",
      labelOverride: "OP",
    },
    {
      id: "room_store",
      type: "room",
      geometry: { kind: "rect", x: 860, y: 605, width: 120, height: 90 },
      labelKey: "mapDesigner.sample.store",
      labelOverride: "Store",
    },
    {
      id: "room_kitchen",
      type: "room",
      geometry: { kind: "rect", x: 740, y: 695, width: 240, height: 215 },
      labelKey: "mapDesigner.sample.kitchen",
      labelOverride: "Detox Kitchen",
    },
    {
      id: "room_16",
      type: "room",
      geometry: { kind: "rect", x: 1030, y: 510, width: 110, height: 95 },
      labelKey: "mapDesigner.sample.rm16",
      labelOverride: "16",
    },
    {
      id: "room_6",
      type: "room",
      geometry: { kind: "rect", x: 1140, y: 510, width: 95, height: 95 },
      labelKey: "mapDesigner.sample.rm6",
      labelOverride: "6",
    },
    {
      id: "room_7b",
      type: "room",
      geometry: { kind: "rect", x: 1235, y: 510, width: 105, height: 140 },
      labelKey: "mapDesigner.sample.rm7b",
      labelOverride: "7b",
    },
    {
      id: "room_8",
      type: "room",
      geometry: { kind: "rect", x: 1175, y: 300, width: 120, height: 90 },
      labelKey: "mapDesigner.sample.rm8",
      labelOverride: "8",
    },
    {
      id: "room_9",
      type: "room",
      geometry: { kind: "rect", x: 1175, y: 390, width: 120, height: 90 },
      labelKey: "mapDesigner.sample.rm9",
      labelOverride: "9",
    },
    {
      id: "room_10",
      type: "room",
      geometry: { kind: "rect", x: 1175, y: 480, width: 120, height: 90 },
      labelKey: "mapDesigner.sample.rm10",
      labelOverride: "10",
    },
    {
      id: "room_11",
      type: "room",
      geometry: { kind: "rect", x: 1175, y: 570, width: 120, height: 90 },
      labelKey: "mapDesigner.sample.rm11",
      labelOverride: "11",
    },
    {
      id: "room_12",
      type: "room",
      geometry: { kind: "rect", x: 1175, y: 660, width: 120, height: 90 },
      labelKey: "mapDesigner.sample.rm12",
      labelOverride: "12",
    },
    {
      id: "room_13",
      type: "room",
      geometry: { kind: "rect", x: 1175, y: 750, width: 120, height: 90 },
      labelKey: "mapDesigner.sample.rm13",
      labelOverride: "13",
    },
    {
      id: "room_14",
      type: "room",
      geometry: { kind: "rect", x: 1175, y: 840, width: 120, height: 90 },
      labelKey: "mapDesigner.sample.rm14",
      labelOverride: "14",
    },
    {
      id: "room_fe",
      type: "room",
      geometry: { kind: "rect", x: 1175, y: 210, width: 190, height: 90 },
      labelKey: "mapDesigner.sample.fe",
      labelOverride: "FE",
    },
    {
      id: "room_sa2",
      type: "room",
      geometry: { kind: "rect", x: 1365, y: 440, width: 110, height: 80 },
      labelKey: "mapDesigner.sample.sa2",
      labelOverride: "SA2",
    },
    {
      id: "wall_horizontal_main",
      type: "wall",
      geometry: { kind: "line", x1: 215, y1: 505, x2: 1295, y2: 505, thickness: 14 },
    },
    {
      id: "wall_vertical_right",
      type: "wall",
      geometry: { kind: "line", x1: 1295, y1: 205, x2: 1295, y2: 940, thickness: 14 },
    },
    {
      id: "wall_vertical_inner",
      type: "wall",
      geometry: { kind: "line", x1: 1160, y1: 205, x2: 1160, y2: 930, thickness: 14 },
    },
    {
      id: "wall_vertical_centre",
      type: "wall",
      geometry: { kind: "line", x1: 690, y1: 505, x2: 690, y2: 910, thickness: 14 },
    },
    {
      id: "wall_entrance_left",
      type: "wall",
      geometry: { kind: "line", x1: 210, y1: 395, x2: 210, y2: 505, thickness: 14 },
    },
    {
      id: "wall_entrance_right",
      type: "wall",
      geometry: { kind: "line", x1: 330, y1: 395, x2: 330, y2: 505, thickness: 14 },
    },
    {
      id: "wall_fe_top",
      type: "wall",
      geometry: { kind: "line", x1: 1160, y1: 205, x2: 1365, y2: 205, thickness: 14 },
    },
    {
      id: "partition_corridor_mid",
      type: "partition",
      geometry: { kind: "line", x1: 700, y1: 505, x2: 700, y2: 905, thickness: 6 },
      labelOverride: "Partition",
    },
    {
      id: "door_entrance",
      type: "door",
      geometry: { kind: "point", x: 285, y: 505, size: 18 },
      wallAttachment: { wallId: "wall_horizontal_main", offset: 70, width: 42 },
    },
    {
      id: "door_fe",
      type: "door",
      geometry: { kind: "point", x: 1160, y: 273, size: 18 },
      wallAttachment: { wallId: "wall_vertical_inner", offset: 68, width: 32 },
    },
    {
      id: "door_sa2",
      type: "door",
      geometry: { kind: "point", x: 1295, y: 485, size: 18 },
      wallAttachment: { wallId: "wall_vertical_right", offset: 280, width: 34 },
    },
    {
      id: "window_right_wing_1",
      type: "window",
      geometry: { kind: "point", x: 1295, y: 360, size: 18 },
      wallAttachment: { wallId: "wall_vertical_right", offset: 155, width: 40 },
    },
    {
      id: "window_right_wing_2",
      type: "window",
      geometry: { kind: "point", x: 1295, y: 720, size: 18 },
      wallAttachment: { wallId: "wall_vertical_right", offset: 515, width: 40 },
    },
    {
      id: "exit_main",
      type: "exit",
      geometry: { kind: "point", x: 270, y: 430, size: 26 },
      labelKey: "mapDesigner.sample.mainExit",
      labelOverride: "Exit",
    },
    {
      id: "fire_exit_fe",
      type: "fireExit",
      geometry: { kind: "point", x: 1215, y: 250, size: 26 },
      labelKey: "mapDesigner.sample.fireExit",
      labelOverride: "Fire Exit",
    },
    {
      id: "roundel_1a",
      type: "roundel",
      geometry: { kind: "point", x: 262, y: 550, size: 30 },
      parentId: "room_1",
    },
    {
      id: "roundel_1b",
      type: "roundel",
      geometry: { kind: "point", x: 302, y: 585, size: 30 },
      parentId: "room_1",
    },
    {
      id: "roundel_2a",
      type: "roundel",
      geometry: { kind: "point", x: 355, y: 548, size: 30 },
      parentId: "room_2",
    },
    {
      id: "roundel_2b",
      type: "roundel",
      geometry: { kind: "point", x: 395, y: 583, size: 30 },
      parentId: "room_2",
    },
    {
      id: "roundel_8a",
      type: "roundel",
      geometry: { kind: "point", x: 1202, y: 330, size: 28 },
      parentId: "room_8",
    },
    {
      id: "roundel_8b",
      type: "roundel",
      geometry: { kind: "point", x: 1252, y: 365, size: 28 },
      parentId: "room_8",
    },
    {
      id: "roundel_9a",
      type: "roundel",
      geometry: { kind: "point", x: 1202, y: 420, size: 28 },
      parentId: "room_9",
    },
    {
      id: "roundel_9b",
      type: "roundel",
      geometry: { kind: "point", x: 1252, y: 455, size: 28 },
      parentId: "room_9",
    },
    {
      id: "label_pt",
      type: "label",
      geometry: { kind: "point", x: 770, y: 315, size: 20 },
      labelKey: "mapDesigner.sample.pt",
      labelOverride: "PT",
      parentId: "zone_courtyard",
    },
  ],
};
