using System.ComponentModel.DataAnnotations;
namespace Acutis.Community.Api;
public sealed class CommunityTenant { public Guid Id { get; set; } [MaxLength(160)] public string OrganisationName { get; set; }=""; public bool IsDemo { get; set; } }
public sealed class CommunityMembership { public Guid Id { get; set; } public Guid TenantId { get; set; } [MaxLength(200)] public string ExternalSubject { get; set; }=""; public string RolesJson { get; set; }="[]"; public bool IsActive { get; set; }=true; public CommunityTenant Tenant { get; set; }=null!; }
public sealed class CommunityParticipant { public Guid Id { get; set; } public Guid TenantId { get; set; } [MaxLength(160)] public string DisplayName { get; set; }=""; [MaxLength(160)] public string? PreferredName { get; set; } [MaxLength(80)] public string? Phone { get; set; } [MaxLength(200)] public string? Email { get; set; } [MaxLength(200)] public string? ReferralSource { get; set; } [MaxLength(40)] public string Status { get; set; }="active"; [MaxLength(160)] public string StaffSubject { get; set; }=""; [MaxLength(160)] public string StaffDisplayName { get; set; }=""; public DateTime CreatedAtUtc { get; set; } public DateTime UpdatedAtUtc { get; set; } }
public sealed class CommunityAppointment { public Guid Id { get; set; } public Guid TenantId { get; set; } public Guid? ParticipantId { get; set; } [MaxLength(160)] public string StaffSubject { get; set; }=""; [MaxLength(160)] public string StaffDisplayName { get; set; }=""; [MaxLength(60)] public string AppointmentType { get; set; }="community-session"; [MaxLength(200)] public string Title { get; set; }=""; public DateTime StartsAtUtc { get; set; } public DateTime EndsAtUtc { get; set; } [MaxLength(40)] public string DeliveryMode { get; set; }="in-person"; [MaxLength(40)] public string Status { get; set; }="scheduled"; public string? Notes { get; set; } public DateTime CreatedAtUtc { get; set; } public DateTime UpdatedAtUtc { get; set; } public CommunityParticipant? Participant { get; set; } }
public sealed class CommunityAssessment { public Guid Id { get; set; } public Guid TenantId { get; set; } public Guid ParticipantId { get; set; } [MaxLength(40)] public string AssessmentType { get; set; }="initial"; public string CaptureJson { get; set; }="{}"; public DateTime CompletedAtUtc { get; set; } [MaxLength(160)] public string CompletedBySubject { get; set; }=""; }
public sealed class CommunityCarePlan { public Guid Id { get; set; } public Guid TenantId { get; set; } public Guid ParticipantId { get; set; } [MaxLength(40)] public string Status { get; set; }="draft"; public string CaptureJson { get; set; }="{}"; public DateOnly? ReviewDate { get; set; } public DateTime CreatedAtUtc { get; set; } public DateTime UpdatedAtUtc { get; set; } }
public sealed class CommunityFormDefinition { public Guid Id { get; set; } public Guid TenantId { get; set; } [MaxLength(100)] public string Code { get; set; }=""; public int Version { get; set; } public string SchemaJson { get; set; }="{}"; [MaxLength(30)] public string Status { get; set; }="draft"; }
public sealed class CommunityFormAssignment { public Guid Id { get; set; } public Guid TenantId { get; set; } public Guid FormDefinitionId { get; set; } public Guid ParticipantId { get; set; } public DateTime AssignedAtUtc { get; set; } [MaxLength(30)] public string Status { get; set; }="assigned"; }
public sealed class CommunityFormResponse { public Guid Id { get; set; } public Guid TenantId { get; set; } public Guid AssignmentId { get; set; } public string AnswersJson { get; set; }="{}"; [MaxLength(30)] public string Status { get; set; }="draft"; public DateTime UpdatedAtUtc { get; set; } }
public sealed class CommunityAuditEvent { public Guid Id { get; set; } public Guid TenantId { get; set; } [MaxLength(200)] public string ExternalSubject { get; set; }=""; [MaxLength(80)] public string Action { get; set; }=""; [MaxLength(120)] public string EntityType { get; set; }=""; [MaxLength(200)] public string EntityId { get; set; }=""; public DateTime OccurredAtUtc { get; set; } public string MetadataJson { get; set; }="{}"; }
