public record ResidentResponse(
    Guid Id,
    string SocialSecurityNumber,
    DateTime DateOfBirth,
    int Age,
    DateTime DateOfAdmission,
    string FirstName,
    string? MiddleName,
    string Surname,
    bool IsPreviousResident,
    Guid PrimaryAddictionId,
    string PrimaryAddictionName,
    List<string> SecondaryAddictions,
    string NationalityName,
    bool IsCompleted,
    string? CompletedBy,
    DateTime? CompletedAt,
    string? PhotoUrl,
    List<string> Documents
);
